### ISSUE TITLE
SQUARE_GIFT_CARD_V2 tender type throws error in ruby #list_payments

### ISSUE THREAD

**Issue by brundage** [square/connect-api-specification#106]
The tender type validator in the ruby gem throws a RuntimeError when the API returns SQUARE_GIFT_CARD_V2 as a tender.

`/home/brundage/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/square_connect-2.6.0.192/lib/square_connect/models/v1_tender.rb:210:in 'card_brand=': invalid value (SQUARE_GIFT_CARD_V2) for 'card_brand', must be one of ["OTHER_BRAND", "VISA", "MASTER_CARD", "AMERICAN_EXPRESS", "DISCOVER", "DISCOVER_DINERS", "JCB", "CHINA_UNIONPAY", "SQUARE_GIFT_CARD"]. (ArgumentError)
`

Code from `square_connect/models/v1_tender.rb` version 2.6.0 line 210

```
    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] card_brand Object to be assigned
    def card_brand=(card_brand)
      validator = EnumAttributeValidator.new('String', ["OTHER_BRAND", "VISA", "MASTER_CARD", "AMERICAN_EXPRESS", "DISCOVER", "DISCOVER_DINERS", "JCB", "CHINA_UNIONPAY", "SQUARE_GIFT_CARD"])
      unless validator.valid?(card_brand)
        fail ArgumentError, "invalid value (#{card_brand}) for 'card_brand', must be one of #{validator.allowable_values}."
      end
      @card_brand = card_brand
    end
```

(modified by me to show the returned `card_brand`)

**Comment by StephenJosey** [comment]
Hi @brundage just wanted to confirm that this issue has been resolved. Thanks for bringing it to our attention, and please let us know if you find anything else!

**Comment by brundage** [comment]
Thanks
