### ISSUE TITLE
Maximum valid Money amount off by an order of magnitude (missing a `9` digit)

### ISSUE THREAD

**Issue by sherbondy** [square/connect-api-specification#109]
Hi there,

I originally reported this issue with one of the downstream generated SDK libraries: 

https://github.com/square/connect-python-sdk/issues/69

But after some digging into how Swagger API specs work, I found the corresponding underlying origin of the problem in the Connect API Specification for the Money model here:

[Money Model missing a 9](https://github.com/square/connect-api-specification/blob/5fc0b93364521bc9774d68f77f3807764f5f7725/api.json#L11553)

I've run into "legitimate" responses from the Square Connect API V2 transactions listing tender `cash_details` field where the `buyer_tendered_money` amount was `999999999` (nine-nines) rather than `99999999` (eight-nines), resulting in the deserialization of the response from the connect API failing, causing a whole page of otherwise legitimate transactions results to be discarded.

Hopefully this is a quick patch fix (happy to submit a PR to resolve this).

**Comment by mootrichard** [comment]
So it looks like square/connect-python-sdk#69 has been resolved, you can try this out on the latest version of the Python SDK. I will be closing the issue for now, but if you still run into problems, please let us know so it can be reopened.

**Comment by shaofu88** [comment]
This is fixed.
