### ISSUE TITLE
Firefox, Palemoon and Waterfox / Content Security Policy

### ISSUE THREAD

**Issue by jabcreations** [square/connect-api-specification#113]
I was doing some last audits and discovered that numerous Gecko based browsers are failing some Content Security Policies.

Waterfox 56.2.2: Fail
Palemoon 28.0 (Last major update release on August 16, 2018 to Gecko 56/Firefox 56)
Firefox 52 ESR: Fail
Firefox 57: Fail
Firefox 58: Pass
Firefox 61: Pass

Apparently Gecko 57 and older handle (or outright don't) **Content-Security-Policy** differently than Gecko 58+. Everyone using Palemoon or Waterfox is doing so because of Mozilla's outright anti-end user hostility over the past few years; the ability to control our browsing environment (our work environment) is more important than blindly copying Google. These browsers are all up to date.

The developer console returns _several_ errors such as the following:

> Content Security Policy: The page’s settings blocked the loading of a resource at blob:https://pci-connect.squareup.com/43bee71b-99a1-4ecc-bc8c-a7725e43e49a (“script-src 'unsafe-inline' https://pay.google.com https://www.gstatic.com https://js.squareup.com”).

According to [Can-I-Use](https://caniuse.com/#search=Content%20Security%20Policy) _Content Security Policy 1.0_ is supported by Gecko 56 and _Content Security Policy 2.0_ supports everything except plugins. So this will likely be some sort of minor bug. I would try to offer more insight though I've actually avoided implementing this header in to my platform due to it's excessive complexity and lack of demand from my customer base at the moment. So this looks like it's entirely out of my hands. Could we please get a quick reproduction confirmation?

Besides an unrelated bug I just fixed it appears that my sandbox is able to still work, at least in Waterfox 56. There may be some unknown / non-verbal after effects caused from this bug.

**Comment by sseaman** [comment]
This does not seem related to Suqare's Swagger API specification so we are resolving this issue.  Please reopen if this is still a concern.
