### ISSUE TITLE
Inventory v2 api?

### ISSUE THREAD

**Issue by colelawrence** [square/connect-api-specification#114]
Hello, I was wondering if there was an updated swagger doc somewhere which includes the `/v2/inventory/` endpoints.

I guess I'm looking in the wrong place or this is out of date.

Thanks!

**Comment by StephenJosey** [comment]
@colelawrence sorry about that, you're right I did misunderstand! We've just pushed out an update to this repo that should include the latest API changes (including Inventory V2). Please let me know if this works for you.
