### ISSUE TITLE
Spec has not been updated for version 2022-12-14

### ISSUE THREAD

**Issue by johnbona** [square/connect-api-specification#188]
Hello!

We generate a Swift client from these specs and when attempting to update it to the latest version, noticed that even though was a PR (#187) to update the spec to version 2022-12-14, only the examples in the JSON were updated. 

The API and models still reflect version 2022-11-16 and the new [RetrieveTokenStatus](https://developer.squareup.com/reference/square/oauth-api/retrieve-access-token-status) endpoint is not present:

<img width="401" alt="image" src="https://user-images.githubusercontent.com/1079281/211171166-688d6af6-db39-41ff-a8eb-bcb056fe3c0d.png">

**Comment by jguze** [comment]
Thank you so much for bringing this to our attention. We made a mistake, and indeed did not update the spec to the correct version. We just took care of this, and the `RetrieveTokenStatus` endpoint should be available now!
