### ISSUE TITLE
Wrong error message for expired nonce suggests nonce not set when it is

### ISSUE THREAD

**Issue by jabcreations** [square/connect-api-specification#84]
Using the API v2 I kept resubmitting the same form details (to create a card for reoccurring charges) while ironing out bugs. I eventually hit error bedrock with the following error returned. Thankfully it did not take me long to realize that this error was returned due to resubmitting the same nonce.

```
[errors] => Array
(
 [0] => stdClass Object
 (
  [category] => INVALID_REQUEST_ERROR
  [code] => MISSING_REQUIRED_PARAMETER
  [detail] => Field must be set
  [field] => card_nonce
 )
)
```
It's be super-snazzy if the server could please be set to return a specific error message that the nonce has expired instead of suggesting that it is not set. My JSON request (obviously) included the nonce so at first it was a bit confusing.

**Comment by jabcreations** [comment]
Actually, this error is _also_ happening when I submit the form with a fresh nonce. Here is the (obfuscated) JSON:
```
{
	"card_nonce": "CBASED1234567890987654321243578",
	"cardholder_name": "John Smith",
	"billing_address": {
		"address_line_1": "123 Main Street",
		"address_line_2": "",
		"locality": "Seattle",
		"administrative_district_level_1": "WA",
		"postal_code": "98118",
		"country": "US"
	}
}
```

**Comment by jabcreations** [comment]
After further debugging it turns out that the user id in the URL was invalid (either empty or 0). In short, with this clarification it would be nice if the error message is still updated though glad I caught that myself.

**Comment by yonpols** [comment]
By user id do you mean the location id on: `POST /v2/locations/{location_id}/transactions`?

**Comment by jabcreations** [comment]
Juan, I've [posted in detail over at Stackoverflow](https://stackoverflow.com/questions/46651132/square-unable-to-create-card-card-nonce-field-must-be-set-when-it-is) as I am not sure if I'm missing something or if I've hit a bug.

**Comment by yonpols** [comment]
Thank you! Let me check what's going on

**Comment by jabcreations** [comment]
Juan, thank you! Please, the **subscription nonce issue is what is holding up my development and testing right now**. I can list users on the live domain so that is a lower priority for me. I code differently than most people so if you need any insight in to anything that I'm doing please feel free to ask.

**Comment by jabcreations** [comment]
Juan, Tristan just pointed out that I had somehow omitted the JSON from the cURL request. So while it was defined it was not sent. Is there a way that you could please enhance the error message to notify developers such as myself that no JSON object was even received to begin with?

**Comment by yonpols** [comment]
Thanks for that. We are going to work on a clearer error for this case.

**Comment by jabcreations** [comment]
**Beautiful!** I'm sure that will save other developers time and aggravation, especially if they're working on the weekends when you guys aren't around to answer questions over at Stack. I really appreciate the positive attitude you guys have in trying to help people out and wish you guys all the best! :-)

**Comment by yonpols** [comment]
Our goal is to allow you to integrate with as little friction as possible. Thank you for reporting this and I'll keep you posted when this is deployed.

**Comment by DanielNi** [comment]
@jabcreations This endpoint now gives you an `"Expected body to be a JSON object."` error if there is no JSON object. Hope this helps!
