### ISSUE TITLE
Empty Response to List Customers

### ISSUE THREAD

**Issue by jabcreations** [square/connect-api-specification#85]
I've spent some time trying to determine why the list customers request wouldn't work and as it turns out it Square's server doesn't like IP addresses (local testing) or localhost (exact same code worked perfectly on my live domain). This was not in the documentation as a requirement and Square's response was empty. There should be some sort of error message about ensuring that tests for whatever features are done from live domains. My local tests were via HTTPS.

**Comment by yonpols** [comment]
Can you explain better how were you testing using a local environment and it didn't work? Square's API can be called from your local environment for you to test. Do you have an example code that doesn't work to share?

**Comment by jabcreations** [comment]
Test environment URLS:
https://127.0.0.1/
https://localhost/

The code I'm using is the exact same file at the exact same save/build.

Here is the function I am pulling in PHP for my current testing. It works fine on live domains though not local domains/IP addresses.

```
function payment_square_user_list($token)
{
echo '<p>'.$token.'</p>';
 $url = 'https://connect.squareup.com/v2/customers';
 $curl_handle = curl_init($url);
 $request_headers = array();
 $request_headers[] = 'Authorization: Bearer '.$token;
 $request_headers[] = 'Accept: application/json';
 //$request_headers[] = 'Content-Length: '.strlen($json);
 //$request_headers[] = 'Content-Type: application/json';
 //curl_setopt($curl_handle, CURLOPT_POSTFIELDS, $json);
 curl_setopt($curl_handle, CURLOPT_CUSTOMREQUEST, 'GET');
 curl_setopt($curl_handle, CURLOPT_HTTPHEADER, $request_headers);
 curl_setopt($curl_handle, CURLOPT_RETURNTRANSFER, 1);
 $result = curl_exec($curl_handle);
 echo '<h2><span>__LIST CUSTOMER__JSON Response</span></h2>';
 $json_response = json_decode($result);
 echo '<pre>';print_r($json_response);echo '</pre>';
}
```

**Comment by yonpols** [comment]
I am able to run it locally with no issues. Can you create a file `test.php` with the following content:
```php
<?php
function payment_square_user_list($token)
{
  echo '<p>'.$token.'</p>';
  $url = 'https://connect.squareup.com/v2/customers';
  $curl_version = curl_version();
  echo'<h2>Curl Version</2><pre>';print_r($curl_version);echo '</pre>';
  $curl_handle = curl_init($url);
  $request_headers = array();
  $request_headers[] = 'Authorization: Bearer '.$token;
  $request_headers[] = 'Accept: application/json';
  curl_setopt($curl_handle, CURLOPT_CUSTOMREQUEST, 'GET');
  curl_setopt($curl_handle, CURLOPT_HTTPHEADER, $request_headers);
  curl_setopt($curl_handle, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($curl_handle, CURLOPT_VERBOSE, 1);
  $result = curl_exec($curl_handle);
  echo '<h2><span>__LIST CUSTOMER__JSON Response</span></h2>';
  $json_response = json_decode($result);
  echo '<pre>';print_r($json_response);echo '</pre>';
}

payment_square_user_list('YOUR ACCESS TOKEN');
```
with **YOUR_ACCESS_TOKEN** replaced and run it locally on the console 
```bash
$ php test.php
```

And check / share with us the response? This will produce a lengthy response where your access token will be present so please remove it before copy/pasting it.
