### ISSUE TITLE
Minor: create user; country returns "ZZ"

### ISSUE THREAD

**Issue by jabcreations** [square/connect-api-specification#92]
Likely a minor bug / some sort of placeholder but the country returned was "ZZ" (without quotes). Personal data obfuscated though reference_id was not. Not sure if there are shadow copies as I'll likely be purging this user for unrelated reasons. AFAIK this does not effect anything. This is on a sandboxed account/user/etc.

> Array
> (
>     [customer] => Array
>         (
>             [id] => 123
>             [created_at] => 2017-11-09T12:44:32.845Z
>             [updated_at] => 2017-11-09T12:44:32.845Z
>             [given_name] => A
>             [family_name] => B
>             [email_address] => 1@example.com
>             [address] => Array
>                 (
>                     [address_line_1] => 123 Main Street
>                     [address_line_2] => 
>                     [country] => ZZ
>                 )
>             [reference_id] => 1510231472
>             [preferences] => Array
>                 (
>                     [email_unsubscribed] => 
>                 )
>         )
> )

**Comment by frojasg** [comment]
ZZ represents "Unknown or Invalid Territory" [1]. 

We return this value when no country was specified when creating the customer.

[1] https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#ZZ
