### ISSUE TITLE
Minor: JavaScript Warnings sans Clear Documentation

### ISSUE THREAD

**Issue by jabcreations** [square/connect-api-specification#95]
One of my goals as a developer is to leave no stone unturned and thus I live a second life in the web console of browsers (predominately Gecko/Firefox/Waterfox's Web Console). I am not sure how to define the following (even if left empty or with the default values) to stop these errors from spawning:

Onload:

ReferenceError: reference to undefined property "fireOnResizeEnd"  paymentform:1:21234
ReferenceError: reference to undefined property "excludeCanvas"  f.js:1:862
ReferenceError: reference to undefined property "maxTouchPoints"

Blur or Focus (ZIP input?)
ReferenceError: reference to undefined property "_keyUpTimer" iframe:31:11943
ReferenceError: reference to undefined property "_keyUpTimer"

Keep in mind that because of the [Gecko/Firefox XML parser bug](https://github.com/square/connect-api-specification/issues/86) I'm forced to load the form on a page within an iframe.

How do I quiet these issues from appearing in the web console? If possible could the documentation please be updated to reflect what is required?

**Comment by brettstimmerman** [comment]
Hi @jabcreations, does the change mentioned in #86 have any effect here?

**Comment by jabcreations** [comment]
@brettstimmerman No effect, when I reported these issues I was only testing the HTML parser (text/html).

They mostly seem to occur with the XML parser (application/xhtml+xml) now that you guys got that fixed (again, thank you); _usually_ parsers aren't the culprit in these kinds of scenarios.

I don't code JavaScript the way most people do (I simply use named functions and anonymous functions for events). I've gone poking in the requested JavaScript files a bit and used a reverse-minifier (about two weeks ago?) though like I said, I don't code like that (not a negative/positive context, just structural) and wasn't able to pin down exactly what your code expects and where. I figure if I did know a placeholder object of some kind would quiet the warnings in the console until I have more time to experiment with the full potential of the form.

**Comment by jabcreations** [comment]
I've noticed this morning (you know, after you guys have gone home for the weekend) that there are one~two dozen requests to the following URL: https://connect.squareup.com/v2/js-error

Is there anything I can do to provide useful feedback?

**Comment by brettstimmerman** [comment]
Hi @jabcreations Thanks for the report! There was a case when the payment form may report additional/extraneous errors, but as of this morning it should no longer happen (though you're likely to continue to notice real errors here and there as you're building).

With respect to your original error report here, are you still in an iframe-within-an-iframe situation? I was under the impression solving #86 would remove that hurdle. Do the errors you reported still occur outside of the nested iframe?

**Comment by jabcreations** [comment]
Thanks to you folks for working on resolving those issues. I've soft-launched and am still using the (single) iframe (there is no iframe - in - another - iframe or second frame of any kind).

I will not have time to work on converting the payment form to be implemented directly in to the page (and out of the iframe) until likely sometime in late January at _absolute earliest_ so I'm afraid I won't be able to provide feedback until that time (aw shucks, less work just during/before the holidays right? 😃).

I have the work on my calendar to update the system away from the iframe and _will_ post the results (good, bad or ugly) after I've verified the system is working in the correct context with my initial tests. If there are any issues in the meantime I can help out with I'm subscribed to all the bugs I'm involved with here.

**Comment by StephenJosey** [comment]
Closing for now as this appears to have been resolved? Please let me know if I'm mistaken!
