### ISSUE TITLE
formnovalidate Not Honored

### ISSUE THREAD

**Issue by jabcreations** [square/connect-api-specification#98]
I discovered that the API does not correctly support the [formnovalidate attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) on submit buttons:

`<input formnovalidate="true" type="submit" value="Pay More Later" />`

Case: I may opt to provide a discount for payment up-front or they can disregard the discount and pay in full within the next 30 days.

I imagine that this _should_ be an easy fix.

**Comment by brettstimmerman** [comment]
Hi @jabcreations, `formnovalidate` is a [boolean attribute](https://www.w3.org/TR/html5/infrastructure.html#sec-boolean-attributes), which can look strange because the value of the attribute is not a boolean `true` or `false`:
```
<input formnovalidate="formnovalidate" type="submit" ...>
```
Or, in "shorthand" with redundant value omitted:
```
<input formnovalidate type="submit" ...>
```

**Comment by jabcreations** [comment]
Ah, the HTML5 standard is incorrectly worded: that is mirroring, not a boolean. Shorthand is invalid in XML and since the standard calls for boolean the value _must_ be true or false. If the people who do not know how to write the standard do not interpret simple aspects of English then that is their fault not mine. Technically you folks can avoid that conflict by simply detecting if `object.hasAttribute('formnovalidate')` at your end in JavaScript.

**Comment by brettstimmerman** [comment]
HTML boolean attributes have been weird for a long time now. For example, the HTML 3.2 spec's section on [`input` elements](https://www.w3.org/TR/REC-html32#input). Specifically, note the definition of the `checked` attribute for checkboxes and radio buttons.

The `novalidate` and `formnovalidate` attributes are handled by the browser. There isn't any JavaScript we can change in this case.
